# Generated by Django 5.0.6 on 2024-07-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_roles_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roles',
            table='Roles',
        ),
    ]
