# Generated by Django 5.0.6 on 2024-06-22 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='linksTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_name', models.CharField(max_length=255)),
                ('link_old_url', models.URLField(max_length=255)),
                ('link_new_url', models.URLField(max_length=255)),
                ('link_views', models.IntegerField()),
                ('user_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='dailyViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_views', models.IntegerField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.linkstable')),
            ],
        ),
        migrations.CreateModel(
            name='monthlyViews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_views', models.IntegerField()),
                ('year', models.IntegerField()),
                ('month', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('link_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.linkstable')),
            ],
        ),
    ]
