# Generated by Django 5.0.6 on 2024-07-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyviews',
            name='link_id',
        ),
        migrations.DeleteModel(
            name='dailyViews',
        ),
        migrations.DeleteModel(
            name='monthlyViews',
        ),
    ]
