# Generated by Django 5.0.6 on 2024-07-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_payoutdata',
            fields=[
                ('user_payoutdata_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField()),
                ('payoutdata_username', models.CharField(max_length=255)),
                ('payoutdata_email', models.EmailField(max_length=254)),
                ('payoudata_address1', models.CharField(max_length=255)),
                ('payoudata_address1_address2', models.CharField(blank=True, max_length=255)),
                ('payoutdata_country', models.CharField(max_length=255)),
                ('payoutdata_zipcode', models.CharField(max_length=255)),
                ('payoutdata_city', models.CharField(max_length=255)),
            ],
        ),
    ]
