# Generated by Django 5.0.6 on 2024-07-23 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayoutData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payoutdata_username', models.CharField(max_length=255)),
                ('payoutdata_email', models.EmailField(max_length=254)),
                ('payoutdata_address1', models.CharField(max_length=255)),
                ('payoutdata_address2', models.CharField(blank=True, max_length=255)),
                ('payoutdata_country', models.CharField(max_length=255)),
                ('payoutdata_zipcode', models.CharField(max_length=255)),
                ('payoutdata_city', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_payoutdata',
            },
        ),
    ]
