# Generated by Django 5.0.6 on 2024-07-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='referral',
            table='referrals',
        ),
    ]
