# ESTE ARCHIVO ESTA CREADO CON EL PROPOSITO DE QUE PUEDAN MANDAR REQUEST DE PAGOS
# AUTOMATICAMENTE SIN NECESIDAD DE QUE LOS USUARIOS LO PIDAN MEDIANTE UN BOTON

# LA IDEA ES QUE ESTO LO PUEDAN ACTIVAR DE MANERA OPCIONA, PERO NO CREO QUE
# TENGAMOS TIEMPO :(