# Generated by Django 5.0.6 on 2024-07-23 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_mnumber',
            field=models.IntegerField(default=0),
        ),
    ]
