# Generated by Django 5.0.6 on 2024-07-24 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_config',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.userconfig'),
        ),
    ]
