# Generated by Django 5.0.6 on 2024-08-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_user_user_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='Enabled_Notifications',
            field=models.BooleanField(default=True),
        ),
    ]
